/**
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

**/

#include<stdio.h>
#include<conio.h>
#include<time.h>
void main()
{
                long a=1,b=2,c=0,sum=0;
                while(1)
                {
                                c=a+b;
                                if(c>4000000)
                                                break;

                                printf("%ld\n",c);
                                if(c%2==0)
                                                sum+=c;
                                a=b;
                                b=c;
                }
                printf("\n\nsum = %ld\n",sum+2);
                printf("EXECUTION TIME = %f",clock()/(float)CLK_TCK);
                system("pause");

}